management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

  server:
    port: 8081


spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/users/**
        - id: productService
          uri: lb://productService
          predicates:
            - Path=/products/**
        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
      filters:
        - name: JwtAuthenticationFilter
          args: { }
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
