server:
  port: 8083  # O cualquier otro puerto

spring:
  application:
    name: orderService
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db 
    username: postgres 
    password: 123456789 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
